spring.application.name=oauth
server.port=8080

# PostgreSQL (we will use later, but keep ready)
spring.datasource.url=jdbc:postgresql://localhost:5432/oauthdb
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#spring.security.user.name=user
#spring.security.user.password=7583e0d3-7a10-4024-8620-b06502a5ac3e